name: Build and Publish Podcast

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * *'  # Every day at 01:15 UTC
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: podcast-publish
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare secrets (GCP TTS)
        env:
          GCP_TTS_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_TTS_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -n "${GCP_TTS_SERVICE_ACCOUNT_JSON}" ]; then 
            mkdir -p .secrets
            echo "$GCP_TTS_SERVICE_ACCOUNT_JSON" > .secrets/gcp_tts_sa.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/.secrets/gcp_tts_sa.json" >> $GITHUB_ENV
          else
            echo "GCP_TTS_SERVICE_ACCOUNT_JSON secret not set; TTS may fail" >&2
          fi

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m newsletter_to_podcast || exit 1

      - name: Commit and push changes (docs/)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs data/state.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: publish feed and audio"
            git push
          fi

      - name: Show feed URL
        run: |
          echo "If GitHub Pages is enabled for 'docs/' on this repo, your feed will be available at:"
          echo "${{ github.server_url }}/${{ github.repository }}/blob/main/docs/feed.xml?raw=1"

